sudo: required
dist: trusty
language: node_js
node_js: '11.6'
branches:
  only:
  - master
before_install:
  - npm install -g yarn --cache-min 999999999
  - npm install aria-fs aria-mocha
install: 
  - yarn install
script:
  - yarn run build && yarn test
after_success:
  - yarn run coveralls