sudo: required
dist: trusty
language: node_js
node_js:
  - '12.16.3'
  - '13.14.0'
  - '14.0.0'
os:
  - windows
  - linux
  - osx
env:
  - YARN_GPG=no
branches:
  only:
  - master
before_install:
  - npm install -g yarn --cache-min 999999999
  - yarn add aria-fs aria-mocha --dev
install: 
  - yarn install
script:
  - yarn build && yarn test
after_success:
  - yarn coveralls