sudo: required
dist: trusty
language: node_js
node_js: '11.6'
branches:
  only:
  - master
before_install:
  - npm install -g yarn --cache-min 999999999
  - yarn add aria-fs aria-mocha --dev
install: 
  - yarn install
script:
  - yarn build && yarn test
after_success:
  - yarn coveralls